### PR TITLE
Don't redirect the prereg page if DEV_BOX is true

### PR DESCRIPTION
**Pull request by kitsuta**
I had to do this anyway to test other changes. Fixes https://github.com/magfest/ubersystem/issues/2580.

### CODE REVIEW

**Comment by earl7399** [comment]
+1

**Comment by kitsuta** [comment]
I'll go ahead and add a notification for 'this form would be turned off' so we can still have insight on how our config would affect the prereg page.

**Comment by kitsuta** [comment]
image
@RobRuana Any better?

**Comment by kitsuta** [comment]
...typo notwithstanding.

**Comment by RobRuana** [comment]
That looks great. I'm okay with this PR as-is, but I think the improvements in the screenshot are great.

**Comment by earl7399** [comment]
guh

should have said "*automatically be redirected*"

rassin' frassin' whippersnappers splittin' infinitives ...

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
ENGLISH ISN'T LATIN

**Pull request merged**
