### PR TITLE
Export of volunteers who worked hours

### PR DESCRIPTION
**Pull request by earl7399**
Fixes magfest/magprime#81

### CODE REVIEW

**Comment by earl7399** [comment]
FWIW, the line it's bitching about isn't anything I touched, and apparently I'm not bright enough to understand the complaint about whitespace, since it looks just like lines close to it.

**Comment by binary1230** [comment]
at the end of reports.py there are a bunch of indents on the last line, our validator is checking for pep8 compliance which seemingly doesn't like that.

**Comment by binary1230** [comment]
pushed a quick fix out

**Comment by binary1230** [comment]
probably a good idea to remove the comment that says ```  # or whatever query we're doing```, other than that code looks solid, +1

**Comment by binary1230** [comment]
+1

**Comment by binary1230** [comment]
oh uh hang on just saw something, the column labels don't match the export.  email-address isn't included in the rows

```
out.writerow(['Badge #', 'Full Name', 'E-mail Address', 'Weighted Hours Scheduled', 'Weighted Hours Worked'])
```

vs 

```
out.writerow([a.badge_num, a.full_name, a.weighted_hours, a.worked_hours])
```

**Comment by binary1230** [comment]
add that and +1

**Comment by binary1230** [comment]
neeeeeeeeeeed. coffeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by earl7399** [comment]
As do I, apparently. Last night.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
I HAVE HAD COFFEE.  +1 MERGE ALL THE THINGS

**Comment by EliAndrewC** [comment]
+1 (belatedly)

**Pull request merged**
