### PR TITLE
MAGStock 7: Correcting checkgroups

### PR DESCRIPTION
**Pull request by Hachi05**
Changing all but one checkbox to checkgroup.

### CODE REVIEW

**Comment by kitsuta** [comment]
...why?

**Comment by Hachi05** [comment]
Cause helpful! And standardized!

**Comment by earl7399** [comment]
So WTH is a "checkgroup"? this is not a standard HTML thing, is it?

**Comment by Hachi05** [comment]
One seems to be what controls allowing a box to be checked, and the other
allows you to click both the box and the text and have the box selected.

**Comment by RobRuana** [comment]
> One seems to be what controls allowing a box to be checked, and the other allows you to click both the box and the text and have the box selected.

Perfect! That should be an easy fix :)

**Comment by RobRuana** [comment]
I have opened issue #2510 which describes your problem, and opened pull request #2511 to fix it!

**Pull request closed without merging**
