### PR TITLE
Fix https://github.com/magfest/ubersystem/issues/739

### PR DESCRIPTION
**Pull request by nathanlitts**

### CODE REVIEW

**Comment by earl7399** [comment]
Looks good!  +1

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
fixes #739

**Comment by binary1230** [comment]
+1

**Comment by binary1230** [comment]
also, welcome aboard!!  you should come hang out with us in Slack chat, hit up code@magfest.org and we'll get you on there.

**Pull request merged**
