### PR TITLE
Badge num to bottom of checkin popup

### LINKED ISSUE #1679: Move the badge number field to the bottom of the check-in popup
A request from Registration's notes: the check-in popup on the attendee admin page currently has the badge number field near the top. It is a lot easier for volunteers if this is actually the last field.

### PR DESCRIPTION
**Pull request by earl7399**
Fixes #1679

### CODE REVIEW

**Comment by kitsuta** [comment]
Whoops, this includes the changes from your other PR.

What you can do to avoid this is, after you've opened the first PR, switch back to the master branch on your local copy - THEN make the next set of changes.

**Comment by kitsuta** [comment]
+1 also

**Comment by earl7399** [comment]
How to fix now?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
+1

**Pull request merged**
