### PR TITLE
add back in bottom corner event-identifying logos

### PR DESCRIPTION
**Pull request by binary1230**
add caution tape image tiled across bottom if DEV_BOX=true

looks like this on a dev box (staging and vagrant):
image

on a non-dev box it drops the 'development' and the caution tape, keeps the logo.

I keep staring at all the different instances and just need a way to tell them apart visually at a glance.

this functionality was commented out in the refactor, mostly this is me just commenting it back in.

goes along with another PR in magprime

### CODE REVIEW

**Comment by binary1230** [comment]
and also, plugins can override the logo by placing a new file named bg-logo.png in the right place.

**Comment by EliAndrewC** [comment]
Looks good to me.

**Comment by kitsuta** [comment]
Oh neat, that's helpful! +1

**Comment by binary1230** [comment]
I WROTE A CSS. WOOOOHOOOOO

**Pull request merged**
