### PR TITLE
Alphabetize Jobs List (requested by @bsmart)

### PR DESCRIPTION
**Pull request by earl7399**
Requested in Slack, can't find issue here.

### CODE REVIEW

**Comment by kitsuta** [comment]
+1, @earl7399 and I did this one together.

**Comment by binary1230** [comment]
looks good to me as long as you guys tested it to make sure changing the order doesn't actually affect anything.  i can't imagine it would, so merge at-will. +1

**Comment by earl7399** [comment]
Muaahahaha

**Comment by EliAndrewC** [comment]
+1

**Pull request merged**
