### PR TITLE
[DO NOT MERGE] At-con check-in fixes

### PR DESCRIPTION
**Pull request by kitsuta**
While this branch was originally intended to work with barcodes, it includes a bunch of bug fixes and workflow improvements for at-con checkin.

@thaeli The modal window still pops up at the bottom of the page, and also I am terrible at styling. Any help is appreciated.

### CODE REVIEW

**Comment by thaeli** [comment]
Hold off on merging this please, I am going to fix the modal and styling in the branch first.

**Comment by kitsuta** [comment]
Yay! My hero!

**Comment by thaeli** [comment]
Vagrantfile is missing in this branch, is that intentional?

**Comment by binary1230** [comment]
There should no longer be any vagrant stuff in this repo, it's all been moved to ubersystem-deploy

Not sure about the AC branch, but in the main branch it's that way.

**Comment by kitsuta** [comment]
This stuff will be covered in a new PR, because it was a bit easier for me to merge this into a new branch.

**Comment by binary1230** [comment]
can we delete this branch?

**Comment by kitsuta** [comment]
Uh, not yet. I still need it for when I eventually implement this for-real. Sorry!

**Comment by binary1230** [comment]
all good, just checking

**Pull request closed without merging**
