### PR TITLE
Merge mag-unstable into master

### PR DESCRIPTION
**Pull request by binary1230**
Merging mag-unstable back into master BIG MERGE

@thaeli cleared that it would be ok to do this, and I'd like to kill mag-unstable and just use master again

### CODE REVIEW

**Comment by binary1230** [comment]
since all of this PR is already peer-reviewed code, because we're already mag-unstable in production, and there was only 1 function of actual merge between master and mag-unstable, I propose we just go ahead and merge this in without doing additional review.  @EliAndrewC  @kitsuta  and @thaeli  you know this branch a bit better than I do so let me know your thoughts, if you guys are good, I'm good.

**Comment by kitsuta** [comment]
:shipit:

**Comment by EliAndrewC** [comment]
+1

**Comment by thaeli** [comment]
Agree, merge it

**Comment by binary1230** [comment]
WOOHOO

**Pull request merged**
