### PR TITLE
WIP: Add priority and sorting to menu items

### PR DESCRIPTION
**Pull request by daredoes**
This commit will do 2/3 things.
1) Add a priority option to MenuItem where  higher numbers end up on the right and lower numbers end up on the left.
2) Sort MenuItems when being sent to the front end first by name, then by priority.

I use this in my own implementation of sideboard and find it to be quite useful due to each plugin adding items to the Menu. 

If this feature is not desire, feel free to discard.

### CODE REVIEW

**Comment by RobRuana** [comment]
This looks cool! Would it change the order menus show up in uber if we deployed it as-is.

**Comment by migetman9** [comment]
Yes! This would change the order the menu's show up in. 

Schedule should become 
Edit Schedule
View Schedule Internal
View Schedule on guidebook.com

**Comment by RobRuana** [comment]
I think I'd prefer the order to be preserved if `priority` is `None`. So anything with a priority is sorted up to the top, and the alphabetical order is used only when two items have the same priority.

So Schedule would stay in the same order, but a plugin could still add items to the top by setting their priority.

Thoughts?

**Comment by migetman9** [comment]
If I'm understanding the change you're talking about correctly, it would be almost achieved by removing the sorted() with the key of x.name. That would change this to just priority sorting, and when two priorities match it would be sorted by declaration. 

Personally, I've found it nice to have the menu automatically sorted by name as it saves me the effort of arranging their declarations. 

I'm not sure how that change would be made as I'm currently in the middle of class so my brain cycles are elsewhere.

**Comment by migetman9** [comment]
As always, feel free to make commits directly onto this branch.

**Comment by migetman9** [comment]
@RobRuana do you have any idea why my last commit broke the unit tests? I am confused.

**Comment by kitsuta** [comment]
You can view the errors by clicking on "Details," next to the failure warnings.

Here's a link to the build tests that are failing: https://travis-ci.org/magfest/ubersystem/jobs/283253731

**Comment by migetman9** [comment]
@kitsuta I saw those, but I still don't understand how the changes in my previous commit caused c.MENU_FILTERED_BY_ITEMS to stop existing? I think I'm missing some piece of logic.

**Comment by kitsuta** [comment]
Oh, that's a good point. That's pretty odd.. maybe it has something to do with the branch conflicts.

**Comment by kitsuta** [comment]
Actually, given your commit that introduced the error, I THINK you introduced an exception in the menuitem class that got swallowed but ended up breaking MENU_FILTERED_BY_ITEM. I'm not at my work machine but I bet that when you try to sort by a priority of `None`, it all breaks.

**Pull request closed without merging**
