### PR TITLE
Update group_confirmation.html

### LINKED ISSUE #1991: Group leader never gets link to own badge
What I expect to happen:
When I purchase a group of badges, the confirmation e-mail should include a link to my own badge so I can edit info, add bundles, etc.

What happens:
No link to the group leader's badge is currently provided.

### PR DESCRIPTION
**Pull request by earl7399**
Add Group Leader badge link
Fixes #1991

### CODE REVIEW

**Comment by kitsuta** [comment]
This looks good - have you tested that this works? This email template may not receive the `attendee` model by default, so you may have to use a different variable to access the info you want (like maybe `group.leader.STUFF`

**Comment by earl7399** [comment]
Nothing running locally, so can't test until staging.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by earl7399** [comment]
This is now running locally (THANKS @kitsuta and @binary1230 )

**Comment by binary1230** [comment]
+1 will test on staging3

**Comment by EliAndrewC** [comment]
+1 (belatedly)

**Pull request merged**
