### PR TITLE
Added regdesk to the watchlist email

### PR DESCRIPTION
**Pull request by timrxd**

### CODE REVIEW

**Comment by kitsuta** [comment]
Why? Regsupport already gets these.

**Comment by timrxd** [comment]
We replaced regdesk with security, then realized we wanted regdesk to get them too.

**Comment by EliAndrewC** [comment]
Fixes #1767

**Comment by kitsuta** [comment]
Whoops, gotcha. I probably shouldn't check email in reverse chronological
order.

**Pull request merged**
