### PR TITLE
put sorting options back into the code

### LINKED ISSUE #1265: MAGClassic 2015: Sorting ability on Staffers Screen
@thaeli  and team, Would it be possible to make the heading of each column on: 
https://classic.uber.magfest.org/uber/registration/staffers
sortable? - so if I clicked an Badge - it would give me an Alpha sort of all the badges, so I can quickly look at Attendee/Staff badges?

We use the Assigned To: section to sort and quickly see who's not assigned anywhere. 

The Hours section to sort through who has hours listed and who hasn't signed up for hours.
  
These where options I had at M13 and we end up use a LOT to manage staff across the board.  
https://prime.uber.magfest.org/m13/registration/staffers?order=weighted_hours

### PR DESCRIPTION
**Pull request by binary1230**
these were omitted from the refactor probably just for the sake of time, I just put them back in.

should fix #1265 

@thaeli probably a good idea to put your eyes on this just to make sure I didn't do anything that breaks the UI.  I think it's pretty straightforward though

### CODE REVIEW

**Comment by kitsuta** [comment]
No, we took these out for Anthrocon when we put in client-side sorting, then Eli removed the client-side sorting. I'm not a huge fan of going back to the server-side sorting - it was much slower because it requires a page reload.

On the other hand, this isn't a particularly extensive change, so if it turns out that it's not just as easy to re-enable client-side sorting, then we can do this for now.

**Comment by binary1230** [comment]
Could we merge this now and make a ticket to re-enable the client-side sorting?  This at least solves the immediate functionality concern, and the client-side sorting is an optimization that we can do whenever.

**Comment by kitsuta** [comment]
This is not an emergency-patch situation, so I don't see the need to merge this before anyone else can weigh in. We have a bunch of bugs to fix before this bug even becomes relevant.

**Comment by EliAndrewC** [comment]
> This is not an emergency-patch situation, so I don't see the need to merge this before anyone else can weigh in. We have a bunch of bugs to fix before this bug even becomes relevant.

I agree, given that we've got reasonably acceptable search functionality, sorting isn't something I'm that worried about, so we'd probably rather do it right than do it fast.

Relatedly: does anyone have any idea how the client-side sorting worked?  I don't remember taking it out, and from looking at
https://github.com/magfest/ubersystem/blob/ac-staging/uber/site_sections/registration.py
I don't see any server-side ajax handlers or anything like that which would facilitate client-side sorting.  Did the client-side sorting only sort the rows on the current page?  If so then I'd recommend merging this PR to go back to server-side sorting and opening a separate issue for sorting improvements.

**Comment by binary1230** [comment]
Yea I looked through the history and didn't see anything resembling client-side searching for this page.  

Since this is something Brent has identified as an important thing for STOPs to use in their workflows, I'd rather see this feature in a less-optimized way and optimized later, than held up and STOPs not have access to it.

Also in this particular case, this particular search is probably not going to be used by anymore than a handful of STOPs crew, so maybe doesn't need to be optimized that much yet.

**Comment by binary1230** [comment]
From Brent: "These were options I had at M13 and we end up using a LOT to manage staff across the board."

**Comment by EliAndrewC** [comment]
At the very least Brent says he wants a working solution by the time we send out the emails to imported staffers on Tuesday night.  I'm personally okay with merging this PR as is, though if someone who knows how the client-side sorting worked wants to explain how we can fix it back to how it was before and/or take a stab at it themselves then that'd be cool too.

**Comment by binary1230** [comment]
since the words "by Tuesday" are in here, I think we should just merge it, considering it's also easy to roll back a revision if someone is going to fix the client-side sorting, and Brent really wanted this functionality.  I went ahead and created this issue here to go back and fix the client-side sorting: https://github.com/magfest/ubersystem/issues/1273

**Comment by kitsuta** [comment]
Yeah, I was totally hoping that Eli would know what happened to disable client-side sorting - since that's not the case, _and_ we've fixed the other bugs, _and_ we have a hard deadline, I'll merge this now and we'll deal with client-side sorting later.

**Pull request merged**
