### PR TITLE
Transfer overridden_price when claiming a group badge

### PR DESCRIPTION
**Pull request by kitsuta**
Fixes https://github.com/magfest/ubersystem/issues/2262

### CODE REVIEW

**Comment by kitsuta** [comment]
This is a pretty major emergency, so merging now.

**Comment by migetman9** [comment]
seems simple and good to me, just double checking for safety's sake

**Comment by earl7399** [comment]
+1

**Comment by EliAndrewC** [comment]
+1 (belatedly)

**Pull request merged**
