### PR TITLE
fixes #2574, use case-insensitive sort for groups table

### LINKED ISSUE #2574: As an admin, I want groups to be sorted alphabetically rather than by ASCII character codes
It seems that capital "Z" comes before lowercase "a" in the default sort on the groups page, just as I remember learning as a wee lad in school. My name is PC-27 and I'm located in the computer lab.

### PR DESCRIPTION
**Pull request by floraline**
Applied str.lower() to sorted key for case-insensitive sort. Is this an appropriate solution to issue #2574?

This is my first time using git and github, and first foray into this project. Constructive advice is welcome!

### CODE REVIEW

**Comment by kitsuta** [comment]
Hi @floraline! Welcome to the codebase, and thank you for contributing! :D

This looks great to me! Gosh, I can't believe DataTables sorting wasn't working at all. When did they even happen? 😰 Nice catch!

**Comment by RobRuana** [comment]
Hi @floraline! +1, belatedly, and welcome to the project!

**Comment by earl7399** [comment]
AHEM!
https://github.com/magfest/ubersystem/issues/2814 (seems to be working on
staging4 , fwiw)

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086

**Comment by kitsuta** [comment]
Huh, yea, that was probably fixed by the change to the <tbody> tag. Nice! 8)

**Pull request merged**
