### PR TITLE
remove old vagrant stuff

### PR DESCRIPTION
**Pull request by binary1230**
hey, is this being used by anyone anymore?  I assume not since there's no Vagrantfile in this dir, but, dunno what AC is currently doing for their deploys.

No rush on pulling the trigger here, we can remove this once everyone has switched over to Docker dev deploys

### CODE REVIEW

**Comment by EliAndrewC** [comment]
As far as I know, this is no longer used, since ``ubersystem-deploy`` took over for this, and Docker is taking over for that.

**Comment by kitsuta** [comment]
I'd wait for @ksonney to approve specifically, but I don't think AC needs this.

**Comment by ksonney** [comment]
We're not using it, our Vagrant test env is bound up in our puppet repo.

**Comment by kitsuta** [comment]
:shipit:

**Comment by binary1230** [comment]
IMMA MERGE IT

**Pull request merged**
