### PR TITLE
Remove analytics.py

### PR DESCRIPTION
**Pull request by earl7399**
for https://phab.thae.li/T61

### CODE REVIEW

**Comment by earl7399** [comment]
How do I undo this, since it isn't against ac-staging?

**Comment by kitsuta** [comment]
You just close the PR, like I'm doing now.

**Comment by kitsuta** [comment]
@earl7399 Hey, you ever gonna resubmit this PR? :)

**Comment by earl7399** [comment]
Done.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Pull request closed without merging**
