### PR TITLE
Set badges to invalid instead of deleting

### PR DESCRIPTION
**Pull request by kitsuta**
This also implements several checks to make sure badges are valid before doing certain things with them, such as checking them in.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
A few stream-of-consciousness thoughts on this:
- We should probably distinguish between dealers which are declined and groups which are deleted.  Or not, I'm not sure - that might be a question for the Marketplace folks.
- Similarly, we probably need a filter on the group list so that we don't show declined/deleted groups by default.
- If someone has a preassigned badge and is marked as invalid, does that shift the badges around them?  It doesn't look like it does at present, but it probably should.
- Relatedly, when an attendee is deleted, those deletes typically cascade to all of the stuff related to that Attendee, e.g. their shifts, hotel assignments, food preferences, etc.  In this implementation that doesn't happen, which is problematic.

That last point is especially problematic, and IMO probably sinks this approach.  If we want to maintain a literal entry in the Attendee table even when an attendee is "deleted" then I think it would be better to let the deletion go through and then re-create a new attendee with the same info and even the same id but with an invalid status.  That would allow us to have the benefits of keeping attendees around but without the troubles of all those foreign key relations.

**Comment by EliAndrewC** [comment]
I have some other thoughts on a possible alternative approach which might also be preferable before I head to bed.  It seems like after we "delete" something there are basically three situations:
- situations where we want the thing to be completely ignored
- situations where we want the thing to show as having been deleted and display an appropriate message/page/whatever
- situations where we want to actually view and interact with the thing (maybe even making further changes to it?)

So long as we handle those cases appropriately, it doesn't matter whether we're deleting or not - that's just an implementation detail.  I'm inclined to think that actually deleting is probably the way to go, so long as we can get an ``Attendee``-like object with all of the fields and methods we need.  Maybe that would be best approached by my original suggestion that we delete and then re-create the attendee, but there are probably some clever things we could do with the ``Tracking`` table or something equivalent.

**Comment by kitsuta** [comment]
Yes, I think deleting and re-creating the attendee and group is probably the way to go. Good point on that - this is a copy from the old ac-staging branch, where we didn't have anything else to deal with (like shifts, etc).

And yea, the Groups page needs a filter much like the Attendee page has.

**Comment by kitsuta** [comment]
Having implemented the new 'safe delete' function, I question whether we actually need to route Groups through this. It takes a lot of extra effort to safe-delete all of a groups' attendees, save them in a list, save the leader id, and then restore everything after deleting and re-creating the Group. I made it work so we can leave it as-is if you think it's necessary, I just wonder if it's overly complex.

**Comment by EliAndrewC** [comment]
Haven't had time to read through the implementation yet, but in general I agree that I don't think we need to route groups through this - I think it's okay if declined dealers and deleted groups are actually deleted from the database and don't need to be put into an invalid state.  And if that makes the implementation cleaner as well then so much the better.

**Comment by thaeli** [comment]
I thought the initial point here was to never delete from the db? From a data integrity perspective I'd rather not even give the uber user DELETE rights on any non-temporary tables..

**Comment by EliAndrewC** [comment]
> I thought the initial point here was to never delete from the db? From a data integrity perspective I'd rather not even give the uber user DELETE rights on any non-temporary tables.

FWIW, I disagree with that as a design choice.  Tracking all changes is one thing, but saying "nothing ever gets deleted from any table in the database" is definitely not how I'd prefer to implement stuff in general.  We can have a broader discussion about deleting things if this is something you feel strongly about, but "nothing ever gets deleted" has never been something that we've all come to a consensus about or agreed to.

**Comment by thaeli** [comment]
I think we should have that broader discussion, yes.

**Comment by kitsuta** [comment]
I actually totally just meant that I don't think groups need to be deleted at all, their status can just be set to invalid/declined.

**Comment by kitsuta** [comment]
By the way, I think this PR is mostly ready now, but I'm currently wondering how to handle personalized badges. Their badge number should be set to 0, right? With the current code, it'll be restored to its original number. Ah... maybe we actually want to keep the number, but not count the badge when calculating new personalized numbers and not shift badges around it. This is surprisingly complex.

**Comment by EliAndrewC** [comment]
> It's a lot easier to look at an attendee details page than to hunt and peck for that person's data in the tracking database.

This is an excellent point, but my intuition is that the solution to this problem is to figure out what our user stories are for what things we want admins to be able to do with deleted stuff and make that easier.  Like, in theory there's no reason why we couldn't make pseudo-Attendee objects out of stuff stored in the tracking table and then show that in search results and even let admins view the form for attendees and groups and such.

To be clear, the current implementation of the tracking table would make that extremely difficult, but my general point is that there's probably an approach which would allow us to do what we want without having to jump through this many hoops to avoid ever deleting anything.  It sounds like the user stories are things like, "As an admin, I'd like to be able to have deleted attendees show up in search results" and "As an admin, I'd like to be able to view (but probably not edit?) the attendee form for deleted attendees" and maybe even "As an user who has clicked a link for an attendee who has since been deleted, I'd like to see a page explaining what has happened instead of just seeing a confusing error message".

Those are all fine user stories, and the best way to implement them may very well be to just mark the attendee as invalid and not delete anything.  Or maybe it's to delete it and be able to reconstruct the object later based on data from something similar to our tracking table.  Or maybe it's something else entirely.  My general thinking is that this is probably best tackled as part of how we handle multi-year/multi-event tracking, since then there's a place we can stick people which is not necessarily in the attendee table but where we can still probably view their data, have them show up in search results, etc.

For now, the decision is whether to try to figure out all of the edge cases to make this PR work or hold off and tackle this as part of a larger effort.  If you think that we're reasonably close to getting this PR ready for merging then that's cool (though I probably won't have time to dive into this in detail until at least this weekend, since I *really* need to work on the import script and some other stuff now that my 12+ hour workdays are probably done for awhile).

**Comment by earl7399** [comment]
I'm actually really unclear why NOT deleting things seems that difficult.
You can still remove attendee's shift and other related entries (either by
deleting them or even better, marking them invalid - so it a decision is
made to reinstate a staffer, their associated shifts can be reinstated as
well) without deleting the original attendee, can't you?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
That's definitely an option, though like the other approaches it's probably a little trickier than it appears at first.  There are currently 8 tables which foreign key into the attendee table.  In some cases like shifts or food preferences we'd probably want to delete them entirely, whereas in other cases they've got nullable foreign keys and are configured as ``SET NULL`` on cascade anyway, so we wouldn't need to delete them.

The trickiest part though is that there are ALSO tables which are defined by plugins which foreign key into the attendee table, so we'd need to figure out how to best handle them.  There are certainly some options there, like having some convention by which we determine whether or not to delete those items which the plugins can mark.

That's probably not enough to sink this approach, but it does add up to things being slightly more complicated than it would appear at first - a common programmer's lament!

**Comment by kitsuta** [comment]
I've actually been thinking about what other columns we'd want to null/delete out, and I think many of them should actually stay. Even things like food_preferences. Basically, if it's not a limited resource like shifts, I don't see a problem with it staying in the database.

**Comment by EliAndrewC** [comment]
> Even things like food_preferences.

The problem is that we have code which spits out reports containing stats on things like how many food-eligible staffers we have and how many of them are vegetarians.  That code assumes that an entry in the ``FoodRestrictions`` table corresponds to a non-deleted attendee.

It's certainly possible for us to modify those reports to follow the foreign key to the attendee table and only count entries which are paired with a non-deleted attendee.  But I'm not wild about the idea that every report we ever write from now until forever needs to do that.  That seems like adding a little bit of complexity everywhere to save ourselves complexity in this one place.

**Comment by kitsuta** [comment]
Ahhh, I see. But keeping data in the DB is common practice, right? Shouldn't a problem like that have been solved by now? Can we put in a universal function that only returns active columns unless otherwise specified?

**Comment by EliAndrewC** [comment]
I dunno, most of the projects I've worked on have just deleted stuff.  If there's a simpler way to handle this stuff I'm not aware of it, though I'm definitely open to suggestions.

**Comment by earl7399** [comment]
Ask some accountants how they feel about records being deleted.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
> Ask some accountants how they feel about records being deleted.

"We store our data in two different database tables, one of which never has anything deleted and has a complete history of all additions, changes, and deletions which have been made to a person's information (and by whom) going back for as long as their information has been tracked in our database."

I definitely get what you're saying, but if the above is NOT a satisfactory answer to an auditor/accountant/whomever then I'd be very surprised.

**Comment by thaeli** [comment]
We've gotten into the "soft delete" vs "hard delete" debate.

My vote is to not merge these changes for now, and think bigger picture
about the entire set of stories around badge deletion/inactivation.

**Comment by kitsuta** [comment]
Fair enough. I'll close this PR and open another one just to implement the check-in changes, then.

**Pull request closed without merging**
