### PR TITLE
unit tests: set defaults values for job_location settings

### PR DESCRIPTION
**Pull request by binary1230**
ensures unit tests work no matter what is in the INI for job_locations
this was causing unit tests to fail in magstock deploys which didn't have "arcade" or "console" depts

fixes https://github.com/magfest/ubersystem/issues/1810

this seems to work great and fixes magstock unit tests

### CODE REVIEW

**Comment by binary1230** [comment]
updated one more section where magstock wasn't happy involving arcade and consoles not being valid Attendee.interests

**Comment by kitsuta** [comment]
LGTM though I'm not super great at unit tests. +1

**Comment by binary1230** [comment]
cool cool. 

@EliAndrewC can you have a look at this one before merge cause it's some serious monkey business

**Comment by kitsuta** [comment]
@EliAndrewC I figure since you've generally been keeping up, you might have lost this email. Dom is waiting for you to look over the PR.

**Comment by EliAndrewC** [comment]
Yeah, I keep meaning to get to this one, it's still in the giant TODO-list that is my inbox.  I should be able to get to it sometime this week.  (This one is just tricky enough that I wanted to give it a little more than a cursory glance, though if not having it is making life difficult for people, I can give an initial cursory review and then dive in deeper later.)

**Comment by binary1230** [comment]
@EliAndrewC any chance you could review this one?  while it's not blocking anything anymore (only Magstock was having issues), it would still be good to get this in

**Comment by EliAndrewC** [comment]
+1

This looks good and in line with what we've previously discussed for how to fix this.

**Comment by binary1230** [comment]
verified tests still pass, merging

**Pull request merged**
