### PR TITLE
Make Duplicates report stop sending the same attendees

### PR DESCRIPTION
**Pull request by kitsuta**
Fixes https://github.com/magfest/ubersystem/issues/1543 by changing attendee's badge status when they're detected as duplicates, which we want anyway because they shouldn't check in without their situation being resolved.

Also stops sending emails for duplicates in unapproved groups, because nothing can be done with them until they've been waitlisted, approved, or declined.

### CODE REVIEW

**Comment by binary1230** [comment]
I forgot to add one comment on the design of this whole thing:

If it's possible, we may want to consider having a config option that's either "using_ticketing_system" or even "send_weekly_duplicate_report" or something similar.

Reason:

For Magfest, it makes complete sense to do what you're doing here and have what was a weekly/daily report be replaced with a one-time email for a specific attendee that becomes a ticket we can close later.

But, for other events using RAMS, this might not be as desirable as having the weekly report, the way we used to do it.  Without the weekly or daily spam, the report data might just get lost in the shuffle.

**Comment by binary1230** [comment]
i.e. if an event isn't using a ticketing system (which a lot of smaller events won't be), then getting our duplicates report not in a daily or weekly fashion makes it less useful to them

**Comment by binary1230** [comment]
hm. ok, I think I had this wrong. actually re-read the code more carefully and I didn't catch at first that we're merging the attendee data of duplicates to eliminate the need for reminders.

if that's the case, we might want to rename this function from ```detect_duplicates()``` (which sounds like it's a ready-only report generation type function that won't modify data) to be something more like ```fix_duplicates()``` (which sounds like it will modify data).

my previous comments about switching reports to be more friendly to events using tickets vs events just using emails still stand though, but it sounds like this isn't an issue here?

**Comment by binary1230** [comment]
btw, maybe out of scope for this PR, but, in the event we don't have any duplicates (i.e. have not sent an email out for that day or there are no dupes), this check will run this query every 6 minutes:
```DaemonTask(detect_duplicates, interval=300)```

Should we decrease that frequency to maybe once per day?  i.e. interval=24*60*60?

I guess in some future universe where we do offload the daemon work onto another container/server this won't matter as much, just, might become a CPU concern if that query ever took a lot of time to run.

**Comment by kitsuta** [comment]
Uh. We are not doing what you described.

The code always removed unpaid duplicates (something I didn't know until I edited the function).

The change just sets them to "New" status. This does two things: it stops them showing up over and over again in reports (because the function just looks at "Completed" attendees) and it prevents duplicate attendees from being checked in (because we don't want that to happen).

I am on the fence about whether other events really care about this. I am not sure we can really accommodate everyone's needs with config settings - this might be something that belongs in a plugin instead.

**Comment by EliAndrewC** [comment]
Regarding the "every 6 minutes" thing, I have two points to note:

1) 300 seconds is 5 minutes and not 6.

2) We don't do the check every 5 minutes either.  If you look carefully, the first thing we do in the function is check whether the email has already been sent, and if it has then we bail out immediately and don't do any of the checking/computation.  So it really only does run once per day; it just does an extremely quick check once every 5 minutes to see whether or not it has already run yet today.

**Comment by EliAndrewC** [comment]
> I am on the fence about whether other events really care about this. I am not sure we can really accommodate everyone's needs with config settings - this might be something that belongs in a plugin instead.

My impression is that any event would care about whether or not they had duplicate badges in the system, which is why I figured this belonged in the core system, but I'm happy to defer to people with more experience working other events on stuff like this.  Moving things into plugins is fairly painless from my perspective, so I don't mind either way.

**Comment by EliAndrewC** [comment]
Can you remind me what the implications are of changing the badge type from ``Completed`` to ``New``?  If they're already paid, then what does changing their badge status accomplish?  (I confess I was never super-clear on the badge types stuff and couldn't find an overview explanation anywhere; that would be a good thing to add in ``configspec.ini`` if nothing else.)

**Comment by binary1230** [comment]
5.....5 minutes.......yea...................I am good at math. fact.

One counterpoint: it is possible the full check can run every 5 minutes.  it checks if an email has been generated for that day, and if so it does bail out.  

But: Emails are only generated *if duplicates are found*. if the system doesn't have any duplicates (i.e. because we fixed them all) then this report is indeed run every 5 minutes.

**Comment by kitsuta** [comment]
@EliAndrewC - I meant, I am not sure events will care about specific logic for emails... or if they do, preferences will be so varied as to be impractical to implement via config.

The "New" badge status simply communicates "this registration has not been completed and is thus not ready to check in." So in this case, although the attendee has paid, the registration isn't _finished_ until we verify that it's not a duplicate badge. But that's a good point about including documentation.

**Comment by EliAndrewC** [comment]
> I meant, I am not sure events will care about specific logic for emails... or if they do, preferences will be so varied as to be impractical to implement via config.

Gotcha.  Yeah, I definitely agree.  And at the end of the day, an even can write a plugin that does whatever they want in code, like they can definitely turn off that ``DaemonTask`` if they really want to and replace it with a different version, or do whatever else they want in the Python code of their plugin.

As for marking badges as ``NEW``, I'm fine with however registration wants to handle that, so I'm +1 on this PR.

**Pull request merged**
