### PR TITLE
Revert "Added attendee update and hotel assigment management methods to API"

### PR DESCRIPTION
**Pull request by kitsuta**
Reverts magfest/ubersystem#3606. This PR broke the build; we'll have to fix it and re-merge it later.

### CODE REVIEW

**Comment by bitbyt3r** [comment]
Is there somewhere I can see the logs of what broke in the build?

**Comment by kitsuta** [comment]
... Oops. I... really should have saved off those messages.

I was planning to pull in the feature branch and test it out to fix it, which I _should_ be able to do today.

**Comment by kitsuta** [comment]
OK, got it fixed. There was a missed comma in line `return HTTPError(400 'Attendee has no field {}'.format(key))`, causing it to fail to start the server. Next time I have to revert a PR after trying to deploy it, I will for sure copy the error message so it's not all on me to figure out what's wrong. 😓

**Comment by bitbyt3r** [comment]
Thank you so much for debugging! I'm sorry I don't have a working environment to test my own code... I can hopefully spend some time this weekend trying to get one running again.

**Pull request merged**
