### PR TITLE
Make admin_table_opts floats

### PR DESCRIPTION
**Pull request by kitsuta**
Fixes https://github.com/magfest/magclassic/issues/41.

### CODE REVIEW

**Comment by thaeli** [comment]
As I noted in the other email thread regarding this issue, I'm really uncomfortable with using floats here. If we need to use decimal numbers let's use the `decimal` library and do proper fixed-point arithmetic. I prefer 0.1 + 0.1 + 0.1 - 0.3 to equal 0, not 5.5511151231257827e-017.

**Comment by kitsuta** [comment]
Yesss, rather embarrassingly I looked up floats after that comment and read it backwards - thinking `float` did simple operations and `decimal` did complex operations. My brain may be slightly fried.

SQLAlchemy has a `Numeric` column type that expects Decimal-type numbers. I don't know what the equivalent is in postgres or if postgres cares. I will look into it next time I get a chance to work on this.

We may have to merge this now though, since it's bordering on an emergency fix.

**Comment by EliAndrewC** [comment]
+1

**Comment by kitsuta** [comment]
This will have to be merged after/with https://github.com/magfest/magclassic/pull/43.

**Comment by binary1230** [comment]
+1

**Comment by binary1230** [comment]
we'll merge this after super reg launch, and will have to run the migration on the prime server as well

**Comment by kitsuta** [comment]
For the information of anyone reading this thread, Dom later found out that migrations are linear (for the time being) and so we ran them all at once.

**Pull request merged**
