### PR TITLE
Removes uber/common.py

### PR DESCRIPTION
**Pull request by RobRuana**

### CODE REVIEW

**Comment by EliAndrewC** [comment]
I probably won't have time to review this in a serious way, but I just wanted to send love for 120 character line widths and finally killing the uber.common module.

**Comment by binary1230** [comment]
woah HE'S GOING FOR IT, LADIES AND GENTLEMEN

**Comment by binary1230** [comment]
only thing I'd say, but honestly, it's not actually that important: it looks like there's 2 things going on here: one is formatting changes, the other is redistributing all the import statements to a per-file thing.  since those are both simple, but vast, changes, it might be a good idea to do them separately if possible just for readability/traceability.   but, if that's in any way complicated, I don't care and go for it.  like Eli I can't really review this one but go for it

**Comment by RobRuana** [comment]
There's not too much to review. It's almost entirely whitespace changes. I went back and fixed some of the more egregious acrobatics I performed to fit into 80 characters 😄 

I'm surprised you endorse killing common.py! I thought that was one of your personal favorites.

If there's one file you should review, it's [uber/__init__.py](https://github.com/magfest/ubersystem/pull/3161/files#diff-75dd4ae458a70c5dac61ff4635f19a36). I tried to figure out everything that needed to be imported to trigger their side-effects, e.g. DaemonTasks, etc...

**Comment by RobRuana** [comment]
Yeah, there's two things: whitespace and imports. I felt comfortable lumping them together because they both fall under the purview of flake8.

In retrospect, it would have made more sense to do them separately, but there's no way I'm going to break this now.

**Comment by EliAndrewC** [comment]
> I'm surprised you endorse killing common.py! I thought that was one of your personal favorites.

It's one of my favorite personal conventions for projects where I'm the only one working on it - not just in Python but other languages, e.g. for small C and C++ projects I would have common.h for the same reason :) 

However, experience has shown that it makes the codebase seem vastly more magical and opaque for newcomers :(

> If there's one file you should review, it's uber/__init__.py. I tried to figure out everything that needed to be imported to trigger their side-effects, e.g. DaemonTasks, etc...

That looks good to me.  I can't think of anything else we'd need to include there, anyway.

**Comment by RobRuana** [comment]
FWIW, `flake8` found very few legit errors. There were a few repeated functions, probably from bad merges. There was one thing that _could_ have been bad, but based on where things were declared, turned out to be harmless.

The `GuestEmail` automated email category was declared twice, with different filters. However, the correct one was being used because it was declared directly before it was used; whereas the wrong one was declared in a totally different file.

Regarding 120 chars vs 80 chars, I still prefer 80 character lines. It is harder to write; but when done with care, I find it easier to read. Especially when I have two files open side-by-side on my laptop screen.

**Pull request merged**
