### PR TITLE
export all DH's name, number, and email to a CSV

### PR DESCRIPTION
**Pull request by migetman9**

### CODE REVIEW

**Comment by binary1230** [comment]
stick this in summary.pu

**Comment by binary1230** [comment]
+1

**Comment by kitsuta** [comment]
Do we, uh, have any concerns about the fact that this lets anyone with summary access get a list of every department head's protected personal information? Wouldn't it have been better in the plugin we made for the general exports?

**Comment by migetman9** [comment]
@kitsuta if a user can get to Summary, can't they also get to attendees to see anyone's Personal Info since they have an admin account?

**Comment by kitsuta** [comment]
@migetman9 Nope, those are actually different checkboxes - Registration and Staffing vs Analytics (the latter is called `c.STATS` in the code).

Functionally speaking most people will have both accesses, so I'm not TOO terribly concerned. But at the same time, effort to pull sensitive data matters. A single click to download every department head's phone number and email address is a lot different than manually searching and pulling information for 50 people - the latter is a lot harder to do if you're some random ne'er-do-well who has a short window of time to duck onto someone else's computer before you're caught.

**Pull request merged**
