### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by kitsuta**
We're having trouble with GitHub _pretending_ to have merge conflicts in upstream when it really doesn't. Hopefully this will fix it.

Also includes support for a working Docker install.

### CODE REVIEW

**Comment by kitsuta** [comment]
As you can see, a bunch of these are literally commits that are already in this repo.

I have no idea.

**Comment by binary1230** [comment]
What I think is going on here is: while it looks like these commits are in the repository already, they actually aren't in magfest/ubersystem. These commits are copies of commits from magfest/ubersystem created in RAMSProject/rams-core.  Likely what happened here is that these commits were created by cherry-picking.  If you check the SHA hashes from the commits here vs the ones in magfest/ubsersystem you will see that they have different hashes, and git doesn't know they are related.

So, instead of drawing new lines on the graph and changing a label, this merge is actually merging a ton of code.  The end result though, as you can see in the diff here, is still identical, but, git still has to treat it as new code, instead of just changing branch labels.

So i.e. git has no way of knowing that this:
https://github.com/magfest/ubersystem/commit/adbba8024b149ffb91488f4e1f16d7ec191bfa22
and this:
https://github.com/RAMSProject/rams/commit/32a8ad097c1c68c2f351b0f7da85252f593b8904
are in fact the same code.  It would be like if two people had changed the same line of code in different unrelated commits, but happened to change it in the exact same way.

The end result here is going to be what you want, although the history at this point is going to look messy with two identical lines.  I don't think this is necessarily a problem, but, in the future, we should probably avoid whatever process (likely lots of cherry-picking) created this duplicate lineage.

So, anyway, TLDR yea it's weird, but it's fine +1

**Comment by binary1230** [comment]
Some other notes on keeping magfest/ubersystem and RAMSProject/rams-core in sync:
1) lots of these kinds of extra crufty weird merges are in our future, and they get harder to deal with when there are actual merge conflicts (luckily, no merge conflicts in this one).  for an example of this when it's medium-tough: https://github.com/magfest/ubersystem/compare/master...Anthrocon-Reg:master
2) it becomes harder to grab individual features vs needing to grab all changes at once, which reduces flexibility
3) we may want to reconsider just getting all development happening inside of RAMSProject/rams-core to eliminate the need to do these extra steps, especially if the goal is to keep the branches in sync, and continue removing magfest-specific stuff from core into mag-specific plugins.  We can always re-fork a magfest branch later if there's some reason to do that.   i.e. at the end of this merge, magfest/ubersystem and RAMSProject/rams-core will be identical again, so we've just done a bunch of extra steps to get a result we could get automatically if magfest devs were directly working on RAMSProject/rams-core to begin with.

**Comment by EliAndrewC** [comment]
+1 on this since the only actual change is the one Dockerfile which won't disrupt anything.

**Comment by kitsuta** [comment]
This was no cherry-picking.

However, that brings up an interesting question... my plan was to do dual pull requests, so that every pull request opened here gets mirrored in upstream. But that sounds like it'll create different commit hashes? We may need to rethink that a little.

If you want to develop inside rams-core, you're gonna have to accept that it'll take a lot longer to get your PRs merged. Magfest develops _way_ too fast to be considered stable for upstream. That was the whole point, remember?

**Comment by binary1230** [comment]
I'm fairly certain (though not entirely) that cherry-picking, and certain forms of rebasing, (and maybe other weird operations in git) are the only things that create copies of commits like this. If you look in the past history, you can see commits before this that were not made copies of which exist in both repos, like this one:

https://github.com/magfest/ubersystem/commit/5f84ce5f5476dbbd7c3c85e9e01c9e3f29ff5740
and 
https://github.com/RAMSProject/rams/commit/5f84ce5f5476dbbd7c3c85e9e01c9e3f29ff5740

note that they have the same hash.  that's what I'd expect normally to happen

@thaeli do you remember which kind of operation you did to pull these commits into RAMSProject/rams-core?  I'd be curious to know.  If it was just a merge of magfest/master -> ramscore/master, I'd expect to see a line on https://github.com/magfest/ubersystem/network from one branch to the other, and not the duplicated commits.

So, I think even if this happens again, it's not a big deal, and if we know what caused it, we can just avoid doing that again if it's possible.  But, I don't think any of this is going to interfere with our normal flow or sync'ing the two projects, so...... whatever : )

---

About dev'ing on RAMSProject/rams-core, I would, personally, like to at least give it a shot develop against that and avoid all this extra merging.  I really do think that lately most of the "really fast/scary magfest development" is really happening inside the magfest-specific plugins, and that the changes going into core are mostly going to be larger, well-tested stuff, like the trusted-by-dept.

I think if we did end up needing to make any big/fast/scary magfest-gotta-have-it-right-now changes, the bulk of those can also get transferred into a magfest-specific plugin.

Right now, those two forks are identical, and no changes were singled out as being unacceptable or too unstable for core.

I'm down for whatever everyone else thinks here, and it ultimately doesn't matter too much, it just creates some extra steps. Mostly, I'm arguing that the effectively, everything Eli and I have written so far is currently inside RAMSProject/rams-core, so we might as well just develop directly against it.  If we do this, we don't have to actively remember to merge things or have the risk that branches diverge.

**Comment by EliAndrewC** [comment]
I don't have a strong preference about which repo we develop out of, but if MAGFest did start developing out of the core RAMS repo, I think it would be best for the MAGFest branch to be different from the main development master, which would let us merge in quick fixes and such without stepping on other events.  (For example, we've made tons of quick-and-dirty on-site fixes and feature additions during every event we've ever had, which mostly get merged in without any kind of code review, and I don't see that changing anytime soon.)

**Comment by thaeli** [comment]
GitHub doesn't have very granular access control, so developing out of core may mean that Magfest will not have control over who has commit access to that branch. Given that, I think it is best if Magfest remains a separate repo and submits PRs to core.

**Comment by kitsuta** [comment]
A process which is now automated.

I mean you guys did notice that, right?

**Comment by kitsuta** [comment]
More importantly, @binary1230 there are often strings of pull requests that end up getting written and merged in quick succession. The code is stable _now_ that it's been in production for a while, but we frequently break stuff while we're working on it.

**Pull request merged**
