### PR TITLE
Merge master into ac-staging

### PR DESCRIPTION
**Pull request by kitsuta**
This is it!

I have written dozens of test scenarios and gone through them manually to ensure this merge will not break horribly. As far as I can possibly tell, this is a working branch that combines the changes made in ac-staging and master over the past few months.

This is the document with the test scenarios I went through: https://docs.google.com/document/d/1uDCmA-WiPUZLoMdXy5EDgsDkuf2nNJyZG2WsZsuW2g4/edit

We're waiting on @EliAndrewC to write up a DB migration script for the AnthroCon database, so no huge rush on merging this until we get that.

### CODE REVIEW

**Comment by earl7399** [comment]
To be clear, you want us to test these, or you have already done so, or
both?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
I've already done the testing for the test scenarios I wrote up.

However, I'm sure there's something I missed when writing them, so once this actually gets merged into ac-staging, it'd behoove us to try to test everything we can collectively imagine we'd need.

**Comment by binary1230** [comment]
I'm slowly coming back on the grid, I'm down to help test this if I get a few minutes.

One thing I can think of before we deploy to AC's production server is to make sure the various parts of the puppet deploy/etc work, our two repos have diverged a bit there too.

We should probably work with the AC folks to allocate a weekend to setting up a testing server, copy their DB over, run all the tests, make sure all the config settings work OK/etc.

There's a useful sideboard entry point I created which dumps the current config from a running uber instance.  you type 'sep print_config' and it'll do it.  it'd be good to make sure that the production AC server and our testing one dump out the same config.

**Comment by thaeli** [comment]
@ksonney will be doing that integration/testing on the AC side. Tagging him in this issue.

**Comment by ksonney** [comment]
So the good news is, this branch still works with our prior deploy stuff, so that's a non-issue. The big issue now is automating the database setup. For the record, we cannot set up another machine to match the command & control setup to match mag, so we need to be able to run the database migration from either a stand-alone script, or from fab/paver stuff in THIS repo. 

Steps taken, FYI:
1. set up a fresh vagrant and init the db
2. verify that we're good using the ac-stage branch
3. change the branch in the hiera data and run puppet
4. watch everything check out and apply ok
5. Error returned:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/default.py", line 326, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column attendee.age_group does not exist
LINE 2: ...e_no_cellphone, attendee.email AS attendee_email, attendee.a...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 142, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 133, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 153, in with_session
    return func(*args, **kwargs)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 251, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 219, in with_rendering
    return render(_get_template_filename(func), result)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 191, in render
    data = renderable_data(data)
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 171, in renderable_data
    data.update({k: getattr(state, k) for k in dir(state) if re.match('^[_A-Z0-9]*$', k)})
  File "/usr/local/anthrocon/plugins/uber/uber/decorators.py", line 171, in <dictcomp>
    data.update({k: getattr(state, k) for k in dir(state) if re.match('^[_A-Z0-9]*$', k)})
  File "/usr/local/anthrocon/plugins/uber/uber/config.py", line 35, in BADGES_SOLD
    individuals = attendees.filter(or_(Attendee.paid == HAS_PAID, Attendee.paid == REFUNDED)).count()
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/orm/query.py", line 2543, in count
    return self.from_self(col).scalar()
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/orm/query.py", line 2349, in scalar
    ret = self.one()
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/orm/query.py", line 2318, in one
    ret = list(self)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/orm/query.py", line 2361, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/orm/query.py", line 2376, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/util/compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/anthrocon/env/lib/python3.4/site-packages/SQLAlchemy-0.8.5-py3.4.egg/sqlalchemy/engine/default.py", line 326, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column attendee.age_group does not exist
LINE 2: ...e_no_cellphone, attendee.email AS attendee_email, attendee.a...
                                                             ^
 'SELECT count(*) AS count_1 \nFROM (SELECT attendee.id AS attendee_id, attendee.group_id AS attendee_group_id, attendee.placeholder AS attendee_placeholder, attendee.first_name AS attendee_first_name, attendee.last_name AS attendee_last_name, attendee.international AS attendee_international, attendee.zip_code AS attendee_zip_code, attendee.ec_phone AS attendee_ec_phone, attendee.cellphone AS attendee_cellphone, attendee.no_cellphone AS attendee_no_cellphone, attendee.email AS attendee_email, attendee.age_group AS attendee_age_group, attendee.reg_station AS attendee_reg_station, attendee.interests AS attendee_interests, attendee.found_how AS attendee_found_how, attendee.comments AS attendee_comments, attendee.for_review AS attendee_for_review, attendee.admin_notes AS attendee_admin_notes, attendee.badge_num AS attendee_badge_num, attendee.badge_type AS attendee_badge_type, attendee.ribbon AS attendee_ribbon, attendee.affiliate AS attendee_affiliate, attendee.shirt AS attendee_shirt, attendee.can_spam AS attendee_can_spam, attendee.regdesk_info AS attendee_regdesk_info, attendee.extra_merch AS attendee_extra_merch, attendee.got_merch AS attendee_got_merch, attendee.registered AS attendee_registered, attendee.checked_in AS attendee_checked_in, attendee.paid AS attendee_paid, attendee.overridden_price AS attendee_overridden_price, attendee.amount_paid AS attendee_amount_paid, attendee.amount_extra AS attendee_amount_extra, attendee.amount_refunded AS attendee_amount_refunded, attendee.payment_method AS attendee_payment_method, attendee.badge_printed_name AS attendee_badge_printed_name, attendee.staffing AS attendee_staffing, attendee.fire_safety_cert AS attendee_fire_safety_cert, attendee.requested_depts AS attendee_requested_depts, attendee.assigned_depts AS attendee_assigned_depts, attendee.trusted AS attendee_trusted, attendee.nonshift_hours AS attendee_nonshift_hours, attendee.past_years AS attendee_past_years \nFROM attendee \nWHERE attendee.paid = %(paid_1)s OR attendee.paid = %(paid_2)s) AS anon_1' {'paid_1': 254570300, 'paid_2': 208168732}

**Comment by binary1230** [comment]
Btw, if you didn't feel like setting up a separate command+control server, you can setup those scripts to run on the production node.  I definitely recommend using that structure and the ubersystem-deploy repo as it already has a ton of good changes in there ready to be merged in, and will have some future stuff like logstash/etc about to be deployed that you can get for free.

Anyway, I'm going to be starting to kick in on some coding stuff in a couple of weeks as we start to launch Magstock and other reg systems for Mag. lemme send an email real quick

**Comment by ksonney** [comment]
Id love to set that up, but let's be honest - it is overkill for a single instance like we are using, and frankly, it over-complucates the setup. We should be able to deploy either way, and at the moment, the puppet configs for ac WORK, so I'm not ini the mood to mess with them. Of bigger concern is the database migration, because if this merges NOW, it breaks things. Database migration needs to be automated as part of THIS repo, and not in a differt repo, as that adds to the complexit, and makes it harder to get others on-board.

**Comment by binary1230** [comment]
Oh right I misunderstood, yea I agree that the DB migration should be part of this repo.

I was looking at this tool (haven't used/tested it yet so not sure if it's good/bad) for doing migrations in a more automated fashion someday, might be worth checking out.  

http://alembic.readthedocs.org/en/latest/

-Dom

**Comment by EliAndrewC** [comment]
Alembic is on my TODO list and I'm planningo n having it ready for the new master branch by the time we launch MAGStock prereg at the beginning of March.

**Comment by ksonney** [comment]
FWIW, the control stuff is GREAT for mag, but isn't mature enough for ac or others - YET. If this was an appliance-based solution, which I'm all for, that has basically an image that brings all this up in  containers on a single server? Let's do it. But not here, not yet, and not on this merge. ;)

**Comment by kitsuta** [comment]
Okay, the latest commit has added a `sep upgrade_db` command with Eli's migration scripts - I've tested this on my local copy, and I'm getting no database errors.

**Comment by ksonney** [comment]
Looking good on a default deploy now and I think we're ready. Let's do this thing, and get everyone on the same codebase.

**Pull request merged**
