### PR TITLE
removed cash/mpoints page from dept checklist

### PR DESCRIPTION
**Pull request by EliAndrewC**
Department Head Checklist items can be configured so that each event can choose their own.  We currently have a cash/mpoints step configured, which points to a page which was specially written for the treasury folks.  This is *extremely* MAGFest specific, so it doesn't belong in the core repo.  Even between different MAGFest events we're going to have slightly different versions of this form anyway.

I'll make a separate PR to re-add it into the MagClassic repo, but this removes it from the core repo.

### CODE REVIEW

**Comment by binary1230** [comment]
cool, and if it makes sense, we could put this in a generic 'magfest' plugin too.  but since there's slight differences.... eh

**Comment by EliAndrewC** [comment]
Yeah, the form will definitely be different, although the page itself will not.  That's not a use case I'd ever really considered, so this might be a good opportunity to make a ``magfest`` repo with any logic common to two or more MAGFest events.  Then we could put the ``site_sections/treasury.py`` file in it, but not the templates, since those will vary.  That might be more trouble than it's worth, in terms of being confusing though.

Food for thought at least.

**Comment by kitsuta** [comment]
+1

My thoughts on this are, put a default form (whatever we think could work as a generic form) in /treasury.py for the magfest repo - that way it won't break anything if we haven't yet made an event-specific plugin. Then the plugin can just override it.

**Comment by EliAndrewC** [comment]
Seems reasonable.  When I get to the point where MAGFest needs this form as well, I'll use that as an opportunity to add this to a common repo.

**Pull request merged**
