### PR TITLE
Add debug logs for _label errors

### LINKED ISSUE #1869: add warning when exception encountered
Can you add a log (probably WARN level, unless it's really something that we don't mind happening and it can be DEBUG) whenever these automatic silent fixes that "should never happen" are applied?

comment from https://github.com/magfest/ubersystem/pull/1868 that we may not have time to fix, if we do then just set this up

### PR DESCRIPTION
**Pull request by kitsuta**
Fixes #1869. Based on feedback from #1868. We don't really mind these _label exceptions, but the logs may help if the data is causing other problems.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
+1 though this could potentially generate a LOT of logs if we actually tripped this to any great degree, like thousands and thousands of lines.  @binary1230: do we have logging turned up to debug in production or do we leave it at ``info``?

**Comment by binary1230** [comment]
I believe we do log debug currently, yea.  it won't show up as a slack alert either unless we enable it

**Comment by kitsuta** [comment]
Er, I can't actually tell if that's a +1 or not.

**Comment by binary1230** [comment]
I just merged master into this.

Of note, the exception now doesn't return 'val' it returns ''

**Comment by binary1230** [comment]
+1

**Pull request merged**
