### PR TITLE
replace wood background with a nicer looking PNG

### PR DESCRIPTION
**Pull request by binary1230**
@cybersenshi set this up in https://github.com/magfest/magstock/pull/64, I'm just extracting it into its own PR and in the base plugin

@cybersenshi plz review the CSS paramaters here, make sure I didn't mess anything up.

here's what it looks like on my box:

image

### CODE REVIEW

**Comment by kitsuta** [comment]
I've got no problem with this, though I'd vaguely prefer to just get rid of the wood texture entirely. :P

**Comment by thaeli** [comment]
+1 for a wood grain-free user experience :)

**Comment by binary1230** [comment]
it's still wood grain btw : )

**Comment by cybersenshi** [comment]
+1 Looks fine.

**Comment by thaeli** [comment]
Ah, in that case -1 do not merge use a non woodgrain texture instead. Too late though, I guess we'll just address that in a different PR.

**Pull request merged**
