### PR TITLE
Allow Staff to use "I'm Not Coming" button

### PR DESCRIPTION
**Pull request by earl7399**
Allow Staff to use "I'm Not Coming" button
Fixes https://github.com/magfest/magclassic/issues/48

### CODE REVIEW

**Comment by kitsuta** [comment]
Although this fix would technically work, there's a reason we didn't do it in the first place. :)

First off, when people use the 'I'm not coming' button, we don't get notified of them using it. This can cause problems, especially since people tend to assume the system is smarter than it is. For example, Joe or Jane Staffer could click that button, assume that they will just get imported into next year instead, and... not. Sad faces all around.

More importantly, although more fixably, invalidating badges does not currently 'cascade' the same way deleting them does. What this means is that Mr/s. Staffer can sign up for shifts, THEN (presumably due to something coming up in their personal lives) decide to say "I'm not coming," but they'll still be marked as working those shifts. And we won't get notified.

At the very least, we'd need to hook up an email to this button that pings us when someone who is NEED_NOT_PAY clicks the button, so we can handle the situation accordingly. That's more work for us though.

**Comment by bds002** [comment]
I don't remember the conversation when we removed the button, but those are valid points and sounds like something I would have complained about before.

**Comment by kitsuta** [comment]
As a separate note - the titles of commit messages are a lot more helpful when they describe what is being done logically speaking rather than literally speaking. So this one might say, "Allow staffers to use I'm Not Coming button." I know GitHub fills the title in for you as "update x.html" but that ends up making things difficult when we're, e.g., trawling through commits trying to find when a change was made.

**Comment by kitsuta** [comment]
@bds002 I think this change was actually prompted by AnthroCon, but yeah, I wanted to be on the cautious side when doing this.

**Comment by earl7399** [comment]
So kill this PR?

**Comment by bds002** [comment]
I am confused as to where this PR stands? We still need a way for staffers to let us know if they aren't coming to an event, but there are a lot of places that have to verified or notified when someone cancels their badge.

**Comment by earl7399** [comment]
The current thought is that since staffers are often assumed to be
returning, they should contact Staffing Ops and/or their (usual) Department
Head to get their badge deferred or otherwise invalidated.

There's currently no checking to see if the badge is associated with
anything (food reqs? shifts?) else, and no notification of anyone, so
allowing what is effectively an anonymous decline leaves too many
(potential) loose threads.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment]
I agree with the thought process here, however if a staffer tells their DH that they aren't coming, the DH is going to go in and hopefully mark the badge as Invalid or deferred, there is still no notice of any changes an email should go to Stops and DH of that department - X staffer's badge has been marked at Invalid, they have been removed from A,BandC shifts etc.  
-- The I'm not coming button that we had in place was an easy way for Staffers to mark themselves as not able to attend when staff verification comes online... maybe it needs to go away once the shift deadline comes into play. Would love to have @EliAndrewC weigh in on this process.

**Comment by earl7399** [comment]
ditto

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
Killing this for now. We'll have to pick this up next year.

**Pull request closed without merging**
