### PR TITLE
Change consent form email date

### PR DESCRIPTION
**Pull request by nickthenewbie1**
Changed parental consent form to e-mail out 2 weeks beforehand instead of just 1.

### CODE REVIEW

**Comment by kitsuta** [comment]
+1

**Comment by kitsuta** [comment]
@EliAndrewC deleting the feature branch breaks the automatic PR into upstream.

**Comment by EliAndrewC** [comment]
> @EliAndrewC deleting the feature branch breaks the automatic PR into upstream.

Roger that, I didn't realize that was the case.

Does that mean that feature branches need to stick around forever then?  I'm not worried about disk space or anything like that, but in general I always liked deleting them after a PR was merged so that it would be easier to look through branches in progress.

**Comment by kitsuta** [comment]
Well, ideally, upstream would delete them. :P

**Comment by EliAndrewC** [comment]
Is the standard procedure to open PRs from feature branches into upstream (in which case deleting the feature branch would be an easy one-click thing after accepting the PR) or to open a single PR from master into upstream?  In the latter case I doubt anyone is going to track down and delete every feature branch.  But from your original comment I assume it's the former, since otherwise you wouldn't care whether the original feature branch had been deleted.

**Comment by kitsuta** [comment]
You are correct, the plan is to merge the feature branches into upstream. I
don't know if it will work out, but I wanted to try automating the process
of opening those PRs.

**Pull request merged**
