### PR TITLE
merge master into remove_abs_urls

### PR DESCRIPTION
**Pull request by binary1230**
ignore, updating feature branch  with latest master

### CODE REVIEW

**Comment by binary1230** [comment]
pulling without CR because it's already in master

**Comment by kitsuta** [comment]
This isn't criticism, but you know you can merge without a PR right? :)

**Comment by EliAndrewC** [comment]
Yeah, although it's not a huge deal, as someone who gets an email every time something like this happens, it creates a non-zero amount of clutter in my inbox and a (admittedly quick) item on my TODO list to click the link to come to this page and see whether it's something I need to look at and then delete the email from my inbox.  So all things being equal, I'd rather not have that happen unless it's a "real" PR, though again it's not a huge deal either way.

**Comment by binary1230** [comment]
yea i was just being lazy and in the back of an SUV trekking across a few states : )  will just merge normally from now on

**Pull request merged**
