### PR TITLE
Remove Supporter badge autoassign

### LINKED ISSUE #1227: Remove Supporter badges
As discussed in https://github.com/magfest/ubersystem/pull/1223, the idea of assigning Supporters a badge has caused us multiple problems in the past because they can't be combined with Staff badges.

For MAGClassic, it would be nice if we stopped assigning Supporter badges and instead added a "Supporter swag" line to the merch field if someone has a kick-in level above Supporter.

So it would display it in three places:
* The modal pop-up we use to check people in
* The message shown when someone checks in
* The Merch page

The new style of Supporter badge would be numberless, and for swag purposes only.

### PR DESCRIPTION
**Pull request by kitsuta**
Fixes #1227.

Unfortunately this includes my last PR because my local copy of master got dirty, but luckily it's a pretty simple change.

I've left a lot of the checks for Supporter badges in because I expect we'll need those later for when we add comped kick-in levels.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
As of this change, we're effectively making ``c.SUPPORTER_BADGE`` no longer a thing, right?  All of those people will just have ``c.ATTENDEE_BADGE`` or whatever their badge type actually is, and they'll just get a personalized badge as part of their swag, if I recall our earlier discussion.

In this case, we should probably go through and remove all of the places where the codebase mentions ``c.SUPPORTER_BADGE``.  Here are the places I found when I grepped for it which are not part of this PR:
- ``uber/templates/static_views/supporters.html`` checks if it's in ``c.PRESASSIGNED_BADGE_TYPES`` before telling people they'll have swag
- ``uber/models.py`` has a couple of places that still check it which are not currently affected by this PR
- ``uber/site_sections/summary.py`` checks its count (that won't break at the moment since it'll just be zero, but if we remove ``c.SUPPORTER_BADGE`` completely it'll start raising an exception)
- ``/uber/templates/registration/form.html`` has a couple of references to it in if-statements

Is there any reason not to just remove ``supporter_badge`` from ``uber/configspec.ini`` and them remove all of these instances of ``c.SUPPORTER_BADGE`` from the codebase?  If we're no longer treating it as its own badge type, then all of those above cases seem like dead code at best.

**Comment by earl7399** [comment]
This seems like the correct way to handle Supporters and their badges in
the new world.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
My original thought was to leave these references in so I can go and convert them later when I (or someone else) refactors kick-ins to not be tied to amount_extra, but now that I'm writing it out I realize that's unnecessary. I'll take them out now.

That being said, I'd like to leave the Supporter badge type inside configspec.ini unless and until we're sure that there are no Supporter badges left in the MAGClassic database.

**Comment by EliAndrewC** [comment]
That seems reasonable.  Since it looks like all of the other references in the code have been removed (I also checked and there are no references to this in the MagClassic plugin) I'll go ahead and merge this now.

**Pull request merged**
