### PR TITLE
Add a function to the ubersystem to display current badge price

### PR DESCRIPTION
**Pull request by migetman9**
Allows @cybersenshi and I to display current badge price on the website through AJAX without exposing sensitive data

### CODE REVIEW

**Comment by binary1230** [comment]
would prefer to see this in registration.py, devtools is for internal stuff and may someday be disabled for production installs or something like that.  just put it next to stats() in registration.py

**Comment by migetman9** [comment]
blah fine

**Comment by binary1230** [comment]
and just to clarify why we're doing this, 

I asked that a separate function be made for this for normal website (external use) instead of /registration/stats for mostly internal use.  in the future, we might put more sensitive info into ```stats`` and lock it down, so one's internal, one's external. 

Web crew is going to use this to display the current price on magfest.org main website.

**Comment by binary1230** [comment]
+1

**Comment by EliAndrewC** [comment]
+1 (belatedly)

**Pull request merged**
