### PR TITLE
Add csv file to get approved dealers information to put on website

### PR DESCRIPTION
**Pull request by migetman9**
Got an email asking to list the vendors on magfest.org, and decided the quickest way to do this was to extract the information from Uber, and beautify it with some Python on my local box. 

**The sooner this is merged, the sooner that info goes on our website for attendees.**

### CODE REVIEW

**Comment by binary1230** [comment]
Can you add the other fields specifically the mailing address, other stuff here too? I was about to make an export like this for tax purposes

**Comment by migetman9** [comment]
Sure whatever I'll just sleep on the plane.

**Comment by migetman9** [comment]
If there are other fields you want, could you just write them in yourself? I just need those first three. I want sleep, but I want this merged.

**Comment by bds002** [comment]
I dont understand the high priority rating on this, listing our vendors to me signifies a shift in the MAGFest way of doing things since the vendors have never been part of the promo of why people come to to MAGFest.

**Pull request merged**
