### PR TITLE
bump version num for uber

### PR DESCRIPTION
**Pull request by binary1230**
messing around with some archive stuff on our older servers, wanted to make sure recent version #'s were incremented correctly.  this doesn't really matter for production servers, only really matters currently for older versions

### CODE REVIEW

**Comment by RobRuana** [comment]
I am very close to rejecting this pull request, simply because our versioning system makes no sense.

**Comment by binary1230** [comment]
yea it's not ... particularly well thought out.  it kinda makes sense on the archive servers as "last time we updated from master", but doesn't make sense in master branch

**Comment by RobRuana** [comment]
My last comment was less snarky/more jerkstore than intended. I have no problem merging this :)

Couldn't you just check the git log on the server to determine where we're at? I don't think we display the version anywhere, right?

**Comment by binary1230** [comment]
It's more like enabling and disabling different backwards compatible stuff
in the code based on the version present.

**Pull request merged**
