### PR TITLE
Fix banner scaling on mobile deviceFix banner scaling on mobile devices

### PR DESCRIPTION
**Pull request by thaeli**

### CODE REVIEW

**Comment by RobRuana** [comment]
Also, I must admit my HTML/CSS skills are maybe a little rusty and out-of-date :smile:

If there's a compelling technical reason why the current pull request is the best method (and why we don't need to care about Firefox) then I'll go ahead and merge it!

**Comment by thaeli** [comment]
Not working correctly in Firefox is indeed a blocker. I'd missed that - had been planning to run BrowserStack to get a bunch of screenshots once it was on an Internet-accessible instance. In the real world, I think this would likely only impact people using Firefox on their phones, but I still think it's a blocker.

I agree with using your Solution #2. Looks like that won't even require changing anything beyond `prereg.css`, in which case I'd suggest we close this PR and make a new one with just those changes.

**Comment by RobRuana** [comment]
You can just push the changes in the the `banner-fix` branch, and I'll squash the history together when I merge this PR :)

Or create a new PR, up to you!

**Comment by thaeli** [comment]
Hmm. does it work if I delete the branch and recreate it?

**Comment by kitsuta** [comment]
@thaeli ...good... question. I've never done that with a PR still open in GitHub.

**Comment by RobRuana** [comment]
I went ahead and added a new commit to this branch that implements the Solution 2 described above.

Please let me know if you'd like me to revert it to what you had before!

Also let me know if this works for everybody :)

**Pull request merged**
