### PR TITLE
Update development-defaults.ini

### PR DESCRIPTION
**Pull request by bds002**
Laying more groundwork for Staff Rooms to be a split management function from general Staff Operations - This should create it's own signature for all Staff Hotel room related functions

### CODE REVIEW

**Comment by EliAndrewC** [comment]
This should probably live in the ``hotel`` repo rather than here, since all of the emails which use it would live there anyway.

When we do that, we should add two things:

1) A new option in ``hotel/configspec.ini`` which defines the option, like
```
staffroooms_email_signature = string
```

2) The entry in ``development-defaults.ini`` just like you have it here.

**Comment by bds002** [comment]
There is already an entry in hotel/configspec.ini... that has the staffrooms info....
So I'm not sure here..... @EliAndrewC

**Comment by kitsuta** [comment]
Was this PR resubmitted for the hotel repo? I can do that if you need, @bds002.

**Comment by EliAndrewC** [comment]
Closing as we clean up old PRs.

**Pull request closed without merging**
