### PR TITLE
Forces the dept head ribbon checkbox to be checked on the reg form, if the attendee is a dept head

### PR DESCRIPTION
**Pull request by RobRuana**
I think this has been confusing people who are used to the old way of doing things.

Ideally we'd remove the dept head ribbon altogether. Maybe sometime in the future...

### CODE REVIEW

**Comment by RobRuana** [comment]
I'm really not sure what the best approach is for this issue. @kitsuta thought it would be a good idea to update the ribbons using a `@presave_adjustment`, and I'm starting to think she was right all along.

**Comment by RobRuana** [comment]
Oh, jeez, I meant to redo this pull request, but never got the chance.

**Comment by kitsuta** [comment]
OK, no problem! I can put it on my todo list if you're still swamped.

**Comment by RobRuana** [comment]
That would be so great!

**Comment by RobRuana** [comment]
Implemented better here:

https://github.com/magfest/ubersystem/pull/3021

**Pull request closed without merging**
