### PR TITLE
add default non-event-specific banner

### PR DESCRIPTION
**Pull request by binary1230**
- SUPER-RAD COOL CON is the BEST CON EVAR

this is so when you do a default deploy of ubersystem without customizing the settings, this banner shows up (replaces the exsting AC 2015 banner)

looks like this:

image

### CODE REVIEW

**Comment by thaeli** [comment]
Also remove the horrible wood grain background AC made me install against my will, and good to go.

**Comment by binary1230** [comment]
hahahah different PR re: wood grain.  I love how everyone hates on stationwagons

**Comment by thaeli** [comment]
Wood grain is awesome on station wagons. Websites are not station wagons. :p

+1

**Comment by EliAndrewC** [comment]
> Websites are not station wagons.

Whoa.  This... changes... everything...

+999999 on the new logo

**Pull request merged**
