### PR TITLE
Banned Email Fix

### LINKED ISSUE #1107: send banned emails to another email list (i.e. security)
Dom says: "As a security staffer, I'd like to know when someone banned attempts to register for Magfest by getting an email sent to the security specific list."

looks like a simple change:

https://github.com/magfest/ubersystem/blob/457bf794df0dc32c26982a928051913e2b0f40fd/uber/site_sections/preregistration.py#L29

Just need to add in there a new _EMAIL config option like SECURITY_EMAIL.  It could default to REGDESK_EMAIL or be overridden by config to be a different address PLUS the original regdesk address.

-Dom

### PR DESCRIPTION
**Pull request by Lusarien**
First pass attempt at a solution, needs testing, forwards banned e-mail registration attempts to security e-mail.

Fixes #1107

### CODE REVIEW

**Comment by Lusarien** [comment]
Haven't tested it yet, looking for some feedback 
@EliAndrewC

**Comment by EliAndrewC** [comment]
Looks great!

> I heard about Mailinator testing, but am unfamiliar with it, is there any documentation available?

Mailinator is just a website where emails can be sent and then you can check them without needing an account.  It's mostly for signing up for things where you're worried about being spammed, or for doing this kind of testing.

For example, I can go to http://magfestemailtest.mailinator.com and I'm immediately presented with an inbox of all messages recently sent to magfestemailtest@mailinator.com without having to actually create that email address or anything like that.

If you're running a local development environment and thus have the ``dev_box`` setting as ``True``, then the system will automatically suppress all emails except those which go to mailinator.com (since it figured those are fine for testing).  This is to prevent us from loading a production database on a test box and then accidentally emailing 10,000 of our real attendees by mistake!

HOWEVER, in order to send emails in the first place, we'll need to get you set up with the API creds to our Amazon account.  We use Amazon SES (Simple Email Service) to send emails, since it's a cheap way to avoid having to run and administer our own email server.  But you'll need some account info to put in your local config file before you can actually send emails at all!

Obviously we can't post those here, but I believe you're working with @binary1230 on getting set up?  If so then perhaps he can find time to get you set up with that.  If not then let me know and I can coordinate with you to get you what you need.

**Comment by thaeli** [comment]
Thanks for the explanation. I'd always wondered that about Mailinator myself. Maybe we should look at making this more developer friendly / flexible, it's kind of an obscure set of dependencies.

**Comment by EliAndrewC** [comment]
> Thanks for the explanation. I'd always wondered that about Mailinator myself. Maybe we should look at making this more developer friendly / flexible, it's kind of an obscure set of dependencies.

I'm definitely open to suggestions.  The main advantage to doing it this way is that emails sent from a dev box are sent using the same mechanism as emails sent in production.  The main downside is (as you point out) it's not obvious to a new developer how to set it up.  We could probably make it friendlier without sacrificing the development-is-the-same-as-production advantage.

**Comment by binary1230** [comment]
@Lusarien hey I finished merging stuff from insert_admin_via_web_ui into master, so, I'm going to close this pull request.  please re-open it and do it from Banned_Email_Fix into master.  you can reference this pull request by writing "#1135" in the description of the new pull request.

in your local setup you can now switch your main branch from insert_admin_via_web_ui and change it to be master now.

if you need help, lemme know.

**Pull request closed without merging**
