### PR TITLE
Attendee Admin Form is showing data from Prereg Page

### PR DESCRIPTION
**Pull request by migetman9**
This may be caused by an Order of Operations Issue. Fixes https://github.com/magfest/ubersystem/issues/2252.

### CODE REVIEW

**Comment by kitsuta** [comment]
I know you and Dom are working on this -- can you explain what you did? The commit message says you split up an `if` statement?

**Comment by kitsuta** [comment]
Oh I see, you split up the really long `if` statement (that I swear I tested as working locally) into two. Conceptually that seems good, so if Dom tells me that this isn't a WIP I'll merge this to test on staging.

**Comment by binary1230** [comment]
need to mention this is UNTESTED since testing it locally is kinda hard.

it looks like we're showing double 'badge name' on supporter attendees in the  registration form.

The original line of code included ```c.PAGE_PATH != '/registration/form'```

Our new line says:
```if c.DONATIONS_ENABLED and c.PAGE_PATH != '/registration/form' and c.PREREG_DONATION_OPTS.length > 1 or attendee.amount_extra```

Which I believe translates to EITHER of these being true it'll let this block show:
1) c.DONATIONS_ENABLED and c.PAGE_PATH != '/registration/form' and c.PREREG_DONATION_OPTS.length > 1
OR
2)  attendee.amount_extra

So therefore, since our supporters have attendee.amount_extra, the c.PAGE_PATH check is ignored

Now the best way to fix this would be to do something like:

```c.PAGE_PATH != '/registration/form' and ((if c.DONATIONS_ENABLED and c.PREREG_DONATION_OPTS.length > 1) or attendee.amount_extra)```

but since (I think? not sure) you can't use parens in django templates, we can instead split the AND part up into two separate nested if statements.

[I think though that this PR might need a quick once over but is the right idea]

**Comment by kitsuta** [comment]
You can't use parentheses in Django templates, yeah. It's annoying.

**Comment by binary1230** [comment]
[and trying to test locally]

**Comment by migetman9** [comment]
This code should look like
`
{% if c.DONATIONS_ENABLED and c.PAGE_PATH != '/registration/form' and (c.PREREG_DONATION_OPTS.length > 1 or attendee.amount_extra) %}
`

correct @kitsuta ?

**Comment by binary1230** [comment]
(vicki said the intention was ok)

**Comment by binary1230** [comment]
OH WOW yea that is an ugly diff.  stupid indents.  this PR just changes the top lines and the bottom line, the indents are screwing stuff up

**Pull request merged**
