### PR TITLE
Fixes magclassic #70: Minor css tweaks to improve supporter options

### PR DESCRIPTION
**Pull request by RobRuana**
Fixes https://github.com/magfest/magclassic/issues/70

Supporter options now look like this:

screen shot 2017-04-10 at 11 31 06 pm

### CODE REVIEW

**Comment by binary1230** [comment]
Hey for any tweaks to the supporter tiers, be sure to test how they look in
mobile

**Comment by RobRuana** [comment]
They look like this in mobile (not perfect, but they match the rest of the page):
screen shot 2017-04-11 at 6 10 31 am

**Comment by binary1230** [comment]
cool, as long as it's usable in mobile (even if a little jank) all good +1

**Comment by binary1230** [comment]
btw unrelated note: those icons were specific to last year's supporter pack items.  we don't have to replace them for labs (low prioirity), just a note that they did match the items we were selling last time.

still, could be cool if someone wanted to put in a science beaker, or lab goggles, or a splicer-related gun or something.  up to the labs team

**Comment by RobRuana** [comment]
Also on an unrelated note: the images in this [pull request](https://github.com/magfest/magclassic/pull/73/files) probably need to be updated as well.

**Comment by kitsuta** [comment]
Nice! Thanks for updating this. :)

**Pull request merged**
