### PR TITLE
Dom's original resend email implementation

### PR DESCRIPTION
**Pull request by RobRuana**
I'm just opening this pull request so we can compare and discuss implementations.

### CODE REVIEW

**Comment by binary1230** [comment]
see https://github.com/magfest/ubersystem/issues/2104 for discussion

**Comment by binary1230** [comment]
heh, so my original thought on this was to advocate that we make ALL emails automated and never call send_email() anywhere but the email daemon. I'm not entirely sure it's possible (it might be?) but I was tracking that here: https://github.com/magfest/ubersystem/issues/1897

**Comment by binary1230** [comment]
also, for the record, right now at this moment in magfest history, I am not going to advocate heavily that we try for these more idealistic goals.  if we need email resending in place for prereg launch, the implementation that @kitsuta wrote that just calls send_email() is fine and realisitcally, we're not going to run into any issues unless a bunch of stuff goes wrong at the same time

**Comment by RobRuana** [comment]
For sure, I'm not advocating for one implementation over the other. Sending emails on a background task would probably be preferable, but we're pretty crunched for time right now. We can always go back and refactor, and with #1897 we even have a reminder.

I had a hunch that Dom was referencing something other than Dare's pull request, and I went on a hunt to see if I could dig it up. Thats all!

😄

**Comment by kitsuta** [comment]
Thanks for pulling this up! :) Gonna close it for now since this is a Future Goal more than something we can currently do.

**Pull request closed without merging**
