### PR TITLE
merge base RAMS project into magfest ubersystem

### PR DESCRIPTION
**Pull request by binary1230**
Sync'ing up with base RAMS fork, includes one fix for group display names

### CODE REVIEW

**Comment by binary1230** [comment]
fix #1651

**Comment by kitsuta** [comment]
+1

**Comment by kitsuta** [comment]
Since Dom didn't actually merge this at the time, and since it was based on the `master` branch, we're going to get a new README that is inaccurate to this repo.

**Comment by binary1230** [comment]
I'm OK with the RAMS readme going in, though after this is merged we should change the Magfest fork's README back to INSTALL.md and not quickstart

**Comment by binary1230** [comment]
ok, doing this.

**Pull request merged**
