### PR TITLE
Radical performance improvements for the menu and sitemap

### PR DESCRIPTION
**Pull request by RobRuana**
Reduces number of db queries by a huge amount.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
+1 nice!

**Comment by RobRuana** [comment]
From 449 database queries down to 4 for the sitemap.

**Comment by EliAndrewC** [comment]
+1000000 even nicer than I thought!

**Comment by binary1230** [comment]
Omggggg

On Dec 11, 2017 9:47 PM, "Eli Courtwright" <notifications@github.com> wrote:

+1000000 even nicer than I thought!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/magfest/ubersystem/pull/3017#issuecomment-350928062>,
or mute the thread

**Pull request merged**
