### PR TITLE
Change license to AGPL3

### PR DESCRIPTION
**Pull request by thaeli**
This updates our license to the Affero General Public License 3.0.

At the time of this commit, there are 11 contributors to this repository. All of them are tagged below. Please reply to this issue with a comment such as "I agree" to note your consent to this license change. 

(Note, if anyone does not agree / does not respond, we will need to remove their contributions from the current version before landing this PR. As only the first 3 contributors listed have more than 10 commits, this shouldn't be too hard, but it's easiest if everyone just replies with their consent.)

- [x] @EliAndrewC
- [x] @binary1230 
- [x] @kitsuta 
- [x] @earl7399 
- [x] @nickthenewbie1
- [x] @JoshMackin 
- [x] @wesleycho 
- [x] @jesusaurus 
- [x] @bitbyt3r 
- [x] @ksonney 
- [x] @thaeli

### CODE REVIEW

**Comment by thaeli** [comment]
I agree

**Comment by wesleycho** [comment]
I agree

**Comment by bitbyt3r** [comment]
I agree

**Comment by kitsuta** [comment]
I agree

**Comment by EliAndrewC** [comment]
I agree

**Comment by binary1230** [comment]
I agree

**Comment by ksonney** [comment]
I agree

**Comment by nickthenewbie1** [comment]
I agree

**Comment by earl7399** [comment]
I agree

**Comment by JoshMackin** [comment]
I agree

**Comment by jesusaurus** [comment]
What is the reasoning behind this change? I don't think this change should be made lightly or without discussion. Aside from the AGPL having a reputation for killing projects, it is also generally avoided by Big Company lawyers because it is untested in court, meaning there is no case law and no legal interpretation yet about how far the network-access clause reaches. If we license ubersystem under the AGPL then it is unknown what work can be considered covered work. I would like to see some serious discussion about what works would be dependent on ubersystem, and I think that magfest should consult a lawyer about the possible consequences and then consider if those possible consequences might deter adoption by others.

**Comment by kitsuta** [comment]
Apologies about that - we accidentally had this discussion almost entirely off-list, as it were. It's actually been under consideration since MAGFest 8.5, and while I'm pretty sure I've mentioned it offhand in one or two unrelated issues, we apparently never made an issue in the tracker to discuss it with everyone. Oops. :\

The big motivation behind converting to AGPL is the inherent SaaS-ness of the software. It'd be very, _very_ easy for a commercial enterprise to wait until we improve the codebase a little bit more, take everything we made, and host a paid SaaS fork without ever contributing back to the OSS community. Anndddd that would suck, so we want to avoid that if possible. This revision seemed like a good point to introduce the license change because the core codebase is now very easy to extend via the plugin API.

To be honest, I am unaware of AGPL killing projects. And to be _frank_, we have a lot bigger/more roadblocks to adoption right now than our license. :) That doesn't mean we shouldn't consider the license in regards to adoption! But I will probably need some clarification on what you're concerned about with that specifically.

**Comment by binary1230** [comment]
@jesusaurus I read the license and mainly if anyone takes this code and runs with it they have to distribute "convey" a copy of the code, which is the main thing AGPL is doing for us vs the existing license.  At this time, I don't want to involve our lawyer in the analysis because, just like we're doing here, it's easy for the copyright holders (us) to re-license the entire system at any time in the future with no consequence to ourselves (it only affects non-copyright holders).  So if AGPL3 is a mistake, we can just change the license later back to whatever we want.

**Comment by binary1230** [comment]
what might be a good idea though is eventually forming a legal organization that governs ubersystem which we can assign the copyright to, then in the future, things like this can be decided by the governing board consisting of the primary developers.

**Comment by binary1230** [comment]
also (unrelated), would like to merge mag-unstable into master as soon as we can.

even if merged mag-unstable before this PR went in, this PR would still be valid and could just re-merge into mag-unstable and merge that into master.  i.e. the order in which this PR goes into master doesn't affect the re-licensing, since all the prior commits on mag-unstable are GPL licensed since we've already distributed (via github) the mag-unstable branch

**Comment by thaeli** [comment]
Go ahead and merge mag-unstable into master.

**Comment by thaeli** [comment]
To address a few points here:

 * I, personally, am uncomfortable with assigning my code copyright to another party. In general, I will not sign Contributor License Agreements; in my opinion, they are unnecessary unless you're doing non-Free Software licensing.

* Any plugins developed with the current API, which is at the Python level, inherit the system's license. So, the requirement to provide source code does extend to these plugins. Right now, that's a little messy because Python plugins have to be used for basic configuration of, say, text.. but that will go away soon. I don't see a need to hold this license change off until we have text configurable in the DB, but am open to putting that dependency if others feel it is important. Same goes for business logic - I don't see the need for that to be kept secret, but if it really is, hey, write it so the secret stuff is stored in the database.

* The Free Software Foundation has lawyers who specialize in FOSS intellectual property issues. They've approved AGPL3. I also would like clarification on what specific concerns @jesusaurus has, so we can discuss them directly.

**Comment by jesusaurus** [comment]
My largest concern was seeing a long list of "I agree"s with no discussion on the matter. But if that discussion has happened elsewhere I would appreciate either logs or a summary. I am also concerned about the legal definition of source code and covered work and how they apply to the specific use of uber as a registration system for cons/fests. I worry that the AGPL could potentially be enforceable on business practices which are dependent on the registration system and that could hinder adoption of uber.

**Comment by kitsuta** [comment]
I expect the easy agreement is because everyone assumed that since the AGPL3 is FSF-approved and close the the well-utilized GPL3, it wasn't gonna make a big difference. That doesn't mean we can't talk about it, though. :)

The summary of what happened off-list is that I said to Eli, Dom, and Thaeli, "Hey, if we really manage to make this program work really well, we're going to be a threat to very big companies with lots of money. We risk having one of those companies come and take our code and host a paid SaaS fork without ever contributing back to the OSS community. I've read that the AGPL covers that and is otherwise the same as GPL 3, so let's switch to that." And everyone else said "yup sounds good."

The intended use of this is definitely not to prevent conventions from running the software on their own servers or from using the software how they want. Probably the easiest way to define what I mean is to say that, if you're charging someone for admin access to the system, that counts as hosting the system "as a Service."

As for the source code, we already treat the configuration files as non-covered - that's data, not code, after all. We do have plans to take config out of files entirely, as @thaeli alluded to earlier.

Does that help to address what you're concerned about? I'm hoping I understood it correctly.

**Comment by thaeli** [comment]
Yes, any modules you write would need to be made available.. but really, no one should be putting secrets or proprietary business logic in code anyway. If an event wanted to keep their business logic secret, they could implement a business logic engine for the affected item and put the specifics in configuration instead.

Data in a database is clearly not covered code. Data in a configuration file is something of a grey area, though we are eliminating configuration files in any case. This does raise another related point, that we may want to be more specific about what licenses apply to what files within the project - that way, documentation / config files / graphics / etc can be licensed differently. I can put together a more detailed pull if needed. This pull just updates the primary LICENSE file and doesn't add headers to every file; actually, it might be easiest to just remove all non-AGPL3 content from this repo and externally reference it. I think that's a few images, the Magfest squarewave logo, a few documentation-ish files, and the config files that we're getting rid of anyway.

**Comment by thaeli** [comment]
I'd also like to link two relevant entries from the GNU GPL3/AGPL3 FAQ.

https://www.gnu.org/licenses/gpl-faq.html#AGPLv3InteractingRemotely
https://www.gnu.org/licenses/gpl-faq.html#AGPLv3ServerAsUser

**Comment by jesusaurus** [comment]
@thaeli thanks for the links, they clearly express the intention of the relevant clauses.

@kitsuta we are not in a position to decide what work is covered work. The license clearly states '"the Program" refers to any copyrightable work licensed under this License' and 'a "covered work" means either the unmodified Program or a work based on the Program,' and 'the "source code" for a work means the preferred form of the work for making modifications to it.' But there is no definition of work in the license, so whether or not something such as configuration files (or business practices in my original example) are considered work based on the Program, and therefore a covered work which requires the same license, is to be decided by the courts if ever a relevant case is decided in court.

I think that I have made my point, and I don't want my two trivial bug fixes to stand in the way of what the primary developers want for the project, so I agree to the license change.

**Comment by thaeli** [comment]
I do think you raise a very good point, and something we should address - per file licensing. You're certainly correct that the scope of a root level LICENSE file alone is less clear than it could be, and that we should be more granular. I think that is a good idea and that to be as clear as possible we should adopt the best practice of per file license headers as appropriate.

Anyone have a tool suggestion for maintaining per file license headers? I'm still thinking we should merge this PR and come back with additional clarifications on the specific files that should have a different license.. That is going to be a very noisy change in the Git history (especially if we touch every file!) and if we do it, I would want to keep it clean and separate of other changes going into master to reduce confusion.

**Comment by thaeli** [comment]
No further objections so I'm going to merge this in now.

**Pull request merged**
