### PR TITLE
Fixes #2437: Changes Legal Name to Name on the prereg confirmation page

### LINKED ISSUE #2437: Change "Legal Name" to "Full Name" on Registration Confirmation
After registering for a badge Uber takes you to the Registration Confirmation page:

image

Although the field says Legal Name, Full Name is used instead. Legal Name doesn't actually need to appear here IMO so maybe we can update the field title to say "Full Name" instead.

### PR DESCRIPTION
**Pull request by RobRuana**

### CODE REVIEW

**Comment by kitsuta** [comment]
Can this actually be a cherry-pick of https://github.com/MidwestFurryFandom/rams/commit/16b83d50815319366065893ebff9ae6dda459eea, to prevent merge conflicts?

**Comment by RobRuana** [comment]
I am pretty sure git will cleanly merge identical files.

**Comment by kitsuta** [comment]
Hm, okay. We can test that theory. +1

**Comment by RobRuana** [comment]
Now I'm actually really curious what will happen! You'll have to let me know if I bust up your repo. If it doesn't work, I promise to cherry-pick the next time this comes up 😄

**Pull request merged**
