### PR TITLE
Fix sum tag in Group form for Jinja2

### PR DESCRIPTION
**Pull request by kitsuta**
This tag was malformed, causing the page to 500 error.

### CODE REVIEW

**Comment by kitsuta** [comment]
What's up with coveralls...?

**Comment by RobRuana** [comment]
Ugh, looks like it's using the `pep8` build which of course covers 0% of the code

**Comment by kitsuta** [comment]
Welp, time to ignore it!

**Comment by EliAndrewC** [comment]
+1 (belatedly)

**Pull request merged**
