### PR TITLE
Make the admin ATD workflow extensible

### PR DESCRIPTION
**Pull request by kitsuta**
Restructures the templates so that plugins are now able to easily add their own fields to the "new" and "check_in_form" pages. Also fixes the check-in functions to accept new parameters without hardcoding them.

### CODE REVIEW

**Comment by kitsuta** [comment]
This is pretty rough and somewhat untested. It also seems that, with very few exceptions, `new_checkin` and `check_in` do functionally the same things. Consider this PR semi-WIP - it should be fine to merge now, but I'm going to try to do a more solid refactor a bit later tonight.

**Comment by kitsuta** [comment]
This ended up being a bit of a monster PR. Here's what's happening:
- I restructured the `new` and `check_in_form` pages to be easily extended by plugins.
- I refactored the `new_checkin` and `check_in` functions to use the same validations, defined in `pre_checkin_check` or moved to `model_checks.py` where appropriate.
- I moved the only unique function left in `check_everything` out to `model_checks.py` and made the attendee details page use just those validations.

I've tested this pretty thoroughly so at-door stuff should work solidly.

**Comment by binary1230** [comment]
love it, a little over my head on the way out the door this morning but I think looks good, I say +1 it

only other suggestion (for any day where, for instance, we're not opening reg tomorrow heh) is if we're moving large chunks of code unmodified from one file to another (like moving that JS to those base templates), try and make that a separate pull request so that it's obvious to the reviewer that there aren't any code changes that need careful review in the large moved block of code.  For today, totally don't worry about this.

**Comment by kitsuta** [comment]
Haha, yea, that was _supposed_ to be the whole PR initially! It wasn't until I was testing my changes that I realized we had no way to add parameters without hard-coding them in the server-side code.

**Pull request merged**
