### PR TITLE
Make badge types configurable

### PR DESCRIPTION
**Pull request by kitsuta**
This was submitted and discussed earlier in PR #1118 - I just forgot to merge it into master after mag-unstable was closed out. It is not yet complete.

### CODE REVIEW

**Comment by kitsuta** [comment]
This is largely done, with a few problems left:

1. There's a spacing issue on the confirm page, the badge types div seems to be placed above the separator div.
2. The confirm page doesn't auto-select the correct badge type.
3. We have Supporter badges but this violates the idea behind the badge type logic.

@EliAndrewC @nickthenewbie1 We need to discuss that last point. I've been pushing for a change to this for some time, since Supporter/Staff badges have posed a logistical problem for us in the past. I'd like to remove the logic that auto-assigns Supporter badges to people with a supporter package. This would be paired with a change to Supporter badges, which would be numberless and "swag-only" badges. Thoughts?

**Comment by nickthenewbie1** [comment]
Usually we use the "extra merch" field for people who are supposed to
receive more than they paid. Is that sufficient?

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by kitsuta** [comment]
We shouldn't even need that, we can just display "and their Supporter badge" if they have a kick-in level above the supporter amount.

Or we could put it in the merch check-in... I wonder how Ryan would feel about that.

**Comment by kitsuta** [comment]
Closing this PR and the related branch - while it does have some stuff not covered by #1224, it's not vital enough to spend any more time on. I'll be creating an issue to get rid of Supporter badges, however.

**Pull request closed without merging**
